export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const FETCH_REGIONS = "REGION/FETCH_REGIONS";
export const CREATE_REGION = "REGION/CREATE_REGION";
export const CHANGE_REGION = "REGION/CHANGE_REGION";
export const DELETE_REGION = "REGION/DELETE_REGION";

export const GET_ERRORS = "ERROR/GET_ERRORS";
export const CLEAR_ERRORS = "ERROR/CLEAR_ERRORS";

export const USER_LOADING = "AUTH/USER_LOADING";
export const USER_LOADED = "AUTH/USER_LOADED";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_FAIL = "AUTH/LOGIN_FAIL";
export const REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const REGISTER_FAIL = "AUTH/REGISTER_FAIL";
export const AUTH_ERROR = "AUTH/ERROR";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";
