export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const FETCH_REGIONS = "REGION/FETCH_REGIONS";
export const CREATE_REGION = "REGION/CREATE_REGION";
export const CHANGE_REGION = "REGION/CHANGE_REGION";
export const DELETE_REGION = "REGION/DELETE_REGION";
